sequenceDiagram
    participant App
    participant Reducer
    participant State
    Note right of State: initial_state
    App ->> Reducer: ADD_TO_CART
    State ->> Reducer: initial_state 
    Reducer ->> State: state_with_item 
    Note right of State: state_with_item 
    App ->> Reducer: TAX
    State ->> Reducer: state_with_item 
    Reducer ->> State: state_with_tax_added 
    Note right of State: state_with_tax_added 


