sequenceDiagram
    participant API
    participant middleware
    participant reducer
    API ->> middleware: MOVE_SHIP { id: enkidu }
    middleware ->> reducer: MOVE_SHIP { id: enkidu: coords: [ x,y ] }
