sequenceDiagram
    API ->> middleware: MOVE_SHIP { id: enkidu }
    middleware ->> reducer: MOVE_SHIP { id: enkidu }
    Note right of reducer: no coords? ignore
    middleware ->> reducer:  MOVE_SHIP  {id: enkidu: coords: [ x,y ] }
    Note right of reducer:  coords? AWRIGHT!
